"""Added user_id to recipe

Revision ID: 7f2e14bb9946
Revises: 
Create Date: 2025-06-28 11:22:32.886268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2e14bb9946'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_recipe_user',  # Nome da constraint
            'users',  # Tabela de referência
            ['user_id'],  # Coluna local
            ['id'],  # Coluna referenciada
            ondelete='CASCADE'  # Opção para quando o usuário for deletado
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
